---
- name: Install dependence api
  become: yes
  shell: |
    cd {{API_FOLDER}} && 
    npm install

- name: Install dependence frontend
  become: yes
  shell: |
    cd {{FRONTEND_FOLDER}} && 
    npm install &&
    npm install -g serve &&
    npm run build
