---
- name: Install dependence api
  become: yes
  shell:
    chdir: "{{API_FOLDER}}"
    cmd: npm install

- name: Install dependence frontend
  become: yes
  shell:
    chdir: "{{FRONTEND_FOLDER}}" 
    cmd: npm install && npm install -g serve && npm run build
