---
- name: Install dependence api
  command: "cd {{API_FOLDER}} && npm install"
  notify:
      - Install dependence api

- name: Install dependence frontend
  command: "cd {{FRONTEND_FOLDER}} && npm install"
  notify:
      - Install dependence frontend

- name: Run api
  command: "cd {{API_FOLDER}} && npm start"
  notify:
      - Run api

- name: Install serve
  command: "cd {{FRONTEND_FOLDER}} && npm install -g serve"
  notify:
      - Install serve

- name: Build frontend
  command: "cd {{FRONTEND_FOLDER}} && npm run build"
  notify:
      - Build frontend

- name: Start frontend
  command: "cd {{FRONTEND_FOLDER}} && serve -s build"
  notify:
      - Run client
