- name: Ensure Git is installed
  apt:
      name: git
      state: latest

- name: Clone the Git repository
  git:
      repo: "{{repo}}"
      dest: "{{dest}}"
      version: "{{version}}"
      accept_hostkey: yes
      key_file: /home/ubuntu/.ssh/id_rsa
