- name: Install ngnix
  apt:
      name: nginx
      state: present

- name: nginx config api
  template:
      src: templates/nginx-api.conf.j2
      dest: /etc/nginx/sites-enabled/site-api.conf
      owner: root
      mode: 0755

- name: nginx config client
  template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/sites-enabled/site.conf
      owner: root
      mode: 0755
  notify:
    - restart nginx

- name: Ensure nginx is running
  service:
      name: nginx
      state: started